#!/bin/bash
#
# Switch script for rtl-tcp and openwebrx
#
# Author: iMakhonin aka Makigo [15.12.2016]
# Email: work.makhonin@gmail.com
#
###

set -e

NAME=Switch
APPNAME=switch
VERSION=0.3
RELEASE=15.12.2016
EMAIL=work.makhonin@gmail.com
DATE=`date +%d/%m`

sr_web="openwebrx"                                                    # Name of Service 1
sr_rtl="rtl-tcp"                                                      # Name of Service 2
info_1=" * Service OpenWebRX is running"                              # Info message for Service 1
info_2=" * Service RTL-TCP is running"                                # Info message for Service 2
info_3=" * SDR services \"$sr_web\" and \"$sr_rtl\" is not running"   # Info message for Not running both services
pause=2                                                               # Delay between stop and start service (sec.)


### Functions ###
service_query() {
  web_status=`service $sr_web status | cut -d " " -f5`
  rtl_status=`service $sr_rtl status | cut -d " " -f5`
}


### Command HELP ###
if [ "$1" == "-h"  ] || [ "$1" == "--help"  ] && [ -z "$2" ];then
  echo "$NAME v$VERSION, application for switch between services openwebrx and rtl-tcp."
  echo "Usage: $APPNAME [KEY]... "
  echo
  echo "  -w,  --web         Switch to \"$sr_web\" or just start."
  echo "  -r,  --rtl         Switch to \"$sr_rtl\" or just start."
  echo "  -o,  --off         OFF both services \"$sr_web\" and \"$sr_rtl\"."
  echo "  -s,  --status      Status of active service."
  echo
  echo "  -h,  --help        Print Help information and exit."
  echo "  -v,  --version     Print Version information and exit."
  echo
  echo "Of all the error in «$APPNAME» write to <$EMAIL>"
  exit 1
###

### Command VERSION ###
elif [ "$1" == "-v"  ] || [ "$1" == "--version"  ] && [ -z "$2" ];then
  echo "Version: $VERSION, Release: $RELEASE"
  exit 1
###

# Command STATUS ###
elif [ "$1" == "-s"  ] || [ "$1" == "--status"  ] && [ -z "$2" ];then
  service_query

  if [ $web_status = "not" ] && [ $rtl_status = "not" ];then
    web_status="OFF"
    rtl_status="OFF"
    web_switch="   "
    rtl_switch="   "
  fi

  if [ $web_status = "not" ];then
    web_status="OFF"
    web_switch="   "
    rtl_switch="==>"
  fi

  if [ $rtl_status = "not" ];then
    rtl_status="OFF"
    rtl_switch="   "
    web_switch="==>"
  fi

  echo -e "    SDR Services status"
  echo -e "    --------------------"
  echo -e "$rtl_switch RTL-TCP is $rtl_status"
  echo -e "$web_switch OPENWEBRX is $web_status"
###

### Command switch to OPENWEBRX ###
elif [ "$1" == "-o"  ] || [ "$1" == "--web"  ] && [ -z "$2" ];then
  service_query

  if [ $web_status = "running" ];then
    echo -e "$info_1"
  else
    if [ $rtl_status = "running" ];then
      service $sr_rtl stop
      sleep $pause
      service $sr_web start
    else
      service $sr_web start
    fi
  fi
###

### Command switch to RTL-TCP ###
elif [ "$1" == "-r"  ] || [ "$1" == "--rtl"  ] && [ -z "$2" ];then
  service_query

  if [ $rtl_status = "running" ];then
    echo -e "$info_2"
  else
    if [ $web_status = "running" ];then
      service $sr_web stop
      sleep $pause
      service $sr_rtl start
    else
      service $sr_rtl start
    fi
  fi
###

### Command OFF both services ###
elif [ "$1" == "-o"  ] || [ "$1" == "--off"  ] && [ -z "$2" ];then
  service_query

  if [ $rtl_status = "running" ];then
    service $sr_rtl stop
  elif [ $web_status = "running" ];then
    service $sr_web stop
  else
    echo -e "$info_3"
  fi
###

else
    echo "Usage command: --help"
    exit 1

fi

exit 0
