#!/bin/bash
#
# Switch script for rtl-tcp and openwebrx
#
# Author: iMakhonin aka Makigo
# Email: work.makhonin@gmail.com
#
###

set -e

NAME=Switch
APPNAME=switch
AUTHOR="Igor Makhonin"
VERSION=0.4.3
RELEASE=14.01.2017
EMAIL=work.makhonin@gmail.com
DATE=`date +%d/%m`

sr_web="webrx1"                                                       # Name of Service 1
sr_rtl="rtl-tcp"                                                      # Name of Service 2
#active=running                                                       # For Upstart
#inactive=not                                                         # For Upstart
active=active                                                         # For Systemd
inactive=inactive                                                     # For Systemd
usage="Usage command:"                                                # Message Usage
info_1=" * Service \"$sr_web\" is running"                            # Info message for Service 1
info_2=" * Service \"$sr_rtl\" is running"                            # Info message for Service 2
info_3=" * SDR services \"$sr_web\" and \"$sr_rtl\" is not running"   # Info message for Not running both services
info_4=" * Service \"$sr_web\" is not running"                        # Info message for Not running WEB service
info_5=" * Service \"$sr_rtl\" is not running"                        # Info message for Not running RTL service
pause=2                                                               # Delay between stop and start service (sec.)

key_w="-w"
key_r="-r"
key_o="-o"
key_s="-s"
key_h="-h, --help"


### Functions ###
service_query() {
  # web_status=`service $sr_web status | cut -d " " -f5`                                 # For Upstart
  # rtl_status=`service $sr_rtl status | cut -d " " -f5`                                 # For Upstart
  web_status=`service $sr_web status | awk -F":" '/Active/ {print $2}' | cut -d "(" -f1` # For Systemd
  rtl_status=`service $sr_rtl status | awk -F":" '/Active/ {print $2}' | cut -d "(" -f1` # For Systemd
}
###

### Command HELP ###
if [ "$1" == "-h"  ] || [ "$1" == "--help"  ] && [ -z "$2" ]; then
  echo "$NAME v$VERSION, application for switch between services openwebrx and rtl-tcp."
  echo "Usage: $APPNAME [KEY]... [COMMAND]... "
  echo
  echo "  -w,  --web [restart|stop]    Switch to \"$sr_web\" or just start."
  echo "  -r,  --rtl [restart|stop]    Switch to \"$sr_rtl\" or just start."
  echo "  -o,  --off                   OFF both services \"$sr_web\" and \"$sr_rtl\"."
  echo "  -s,  --status                Status of active service."
  echo
  echo "  -h,  --help       Show Help information and exit."
  echo "  -v,  --version    Show Version information and exit."
  echo
  echo "About all errors in «$APPNAME» write to <$EMAIL>"
  exit 1
###

### Command VERSION ###
elif [ "$1" == "-v"  ] || [ "$1" == "--version"  ] && [ -z "$2" ]; then
  echo "Version: $VERSION, Release: $RELEASE"
  exit 1
###

# Command STATUS ###
elif [ "$1" == "-s"  ] || [ "$1" == "--status"  ] && [ -z "$2" ]; then
  service_query

  if [ $web_status = "$inactive" ] && [ $rtl_status = "$inactive" ]; then
    #web_status="OFF"
    #rtl_status="OFF"
    web_switch="   "
    rtl_switch="   "
  fi

  if [ $web_status = "$inactive" ]; then
    #eb_status="OFF"
    web_switch="   "
    rtl_switch="==>"
  fi

  if [ $rtl_status = "$inactive" ]; then
    #rtl_status="OFF"
    rtl_switch="   "
    web_switch="==>"
  fi

  echo -e "    Services status"
  echo -e "    ------------------------"
  echo -e "$rtl_switch $sr_rtl\t - $rtl_status"
  echo -e "$web_switch $sr_web\t - $web_status"
###

### Command switch to OPENWEBRX ###
elif [ "$1" == "-w"  ] || [ "$1" == "--web"  ] && [ -z "$2" ]; then
  service_query

  if [ $web_status = "$active" ]; then
    echo -e "$info_1"
  else
    if [ $rtl_status = "$active" ]; then
      service $sr_rtl stop
      sleep $pause
      service $sr_web start
    else
      service $sr_web start
    fi
  fi

elif [ "$1" == "-w"  ] || [ "$1" == "--web"  ] && [ ! -z "$2" ]; then
  service_query

  if [ $web_status = "$active" ]; then
    if [ "$2" == "stop" ]; then
      service $sr_web stop
    elif [ "$2" == "restart" ]; then
      service $sr_web restart
    else
      echo "$usage $APPNAME $key_w [restart|stop]"
    fi
  else
    echo "$info_4"
  fi
###

### Command switch to RTL-TCP ###
elif [ "$1" == "-r" ] || [ "$1" == "--rtl"  ] && [ -z "$2" ]; then
  service_query

  if [ $rtl_status = "$active" ]; then
    echo -e "$info_2"
  else
    if [ $web_status = "$active" ]; then
      service $sr_web stop
      sleep $pause
      service $sr_rtl start
    else
      service $sr_rtl start
    fi
  fi

elif [ "$1" == "-r"  ] || [ "$1" == "--rtl"  ] && [ ! -z "$2" ]; then
  service_query

  if [ $rtl_status = "$active" ]; then
    if [ "$2" == "stop" ]; then
      service $sr_rtl stop
    elif [ "$2" == "restart" ]; then
      service $sr_rtl restart
    else
      echo "$usage $APPNAME $key_r [restart|stop]"
    fi
  else
    echo "$info_5"
  fi
###

### Command OFF both services ###
elif [ "$1" == "-o"  ] || [ "$1" == "--off"  ] && [ -z "$2" ]; then
  service_query

  if [ $rtl_status = "$active" ]; then
    service $sr_rtl stop
  elif [ $web_status = "$active" ]; then
    service $sr_web stop
  else
    echo -e "$info_3"
  fi
###

else
    echo "$usage $key_h"
    exit 1
fi

exit 0
