#!/bin/bash -e
#
# Switch script for rtl-tcp and openwebrx
#
# Author: iMakhonin aka Makigo [14.12.2016]
#
###


DAEMON=switch                                                         # Name of this Daemon
sr_web="openwebrx"                                                    # Name of Service 1
sr_rtl="rtl-tcp"                                                      # Name of Service 2
info_1=" * OpenWebRX is running"                                      # Info message for Service 1
info_2=" * RTL-TCP is running"                                        # Info message for Service 2
info_3=" * SDR services \"$sr_web\" and \"$sr_rtl\" is not running"   # Info message for Not running both services
pause=2                                                               # Delay between stop and start service (sec.)


# Functions.
service_query() {
  web_status=`service $sr_web status | cut -d " " -f5`
  rtl_status=`service $sr_rtl status | cut -d " " -f5`
}

do_status() {
  service_query

  if [ $web_status = "not" ] && [ $rtl_status = "not" ]; then
    web_status="OFF"
    rtl_status="OFF"
    web_switch="   "
    rtl_switch="   "
  fi

  if [ $web_status = "not" ]; then
    web_status="OFF"
    web_switch="   "
    rtl_switch="==>"
  fi

  if [ $rtl_status = "not" ]; then
    rtl_status="OFF"
    rtl_switch="   "
    web_switch="==>"
  fi

  echo -e "    SDR Services status"
  echo -e "    --------------------"
  echo -e "$rtl_switch RTL-TCP is $rtl_status"
  echo -e "$web_switch OPENWEBRX is $web_status"
}

do_web() {
  service_query

  if [ $web_status = "running" ]; then
    echo -e "$info_1"
  else
    if [ $rtl_status = "running" ]; then
      service $sr_rtl stop
      sleep $pause
      service $sr_web start
    else
      service $sr_web start
    fi
  fi
}

do_rtl() {
  service_query

  if [ $rtl_status = "running" ]; then
    echo -e "$info_2"
  else
    if [ $web_status = "running" ]; then
      service $sr_web stop
      sleep $pause
      service $sr_rtl start
    else
      service $sr_rtl start
    fi
  fi
}

do_off() {
  service_query

  if [ $rtl_status = "running" ]; then
    service $sr_rtl stop
  elif [ $web_status = "running" ]; then
    service $sr_web stop
  else
    echo -e "$info_3"
  fi
}


# See how we were called.
case "$1" in

  web|rtl|off|status)
    do_${1}
  ;;

  *)
    echo "Usage: service $DAEMON {web|rtl|off|status}"
    exit 1
  ;;

esac
exit 0
